[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'vim-syntastic/syntastic'

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']

# Unite
[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo      = 'Shougo/neomru.vim'
on_source = ['unite.vim']

[[plugins]]
repo = 'Shougo/unite-outline'
depends = ['unite']

[[plugins]]
repo = 'hewes/unite-gtags'
depends = ['unite']

[[plugins]]
repo = 'Shougo/vimfiler'

# highlight search results
[[plugins]]
repo = 'osyo-manga/vim-anzu'

